[project]
name = "aniso-pooling"
version = "0.1.0"
description = "BSc Thesis project 'Anisotropic Quadratic Forms for Pooling in Deep Learning'"
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Peter Adema", email = "p.j.adema@uva.nl" }
]
dependencies = [
    "altair>=5.5.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "numba-cuda>=0.10.0",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "polars>=1.27.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "tqdm>=4.67.1",
    "pyarrow>=20.0.0",
    # Custom packages:
    "pytorch-numba-extension-jit>=0.1.0",
    "pytorch-nd-semiconv>=0.1.0",
]


[[tool.uv.index]]
name = "torch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true


[tool.uv.sources]
torch = [
    { index = "torch-cu128", marker = "sys_platform != 'darwin'" },
]
torchvision = [
    { index = "torch-cu128", marker = "sys_platform != 'darwin'" },
]

morphological_torch = { path = "replicate/parabolic_pooling_investigation/morphology_package/dist/morphological_torch-0.1.0-cp312-cp312-linux_x86_64.whl", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" }

[dependency-groups]
dev = [
    "hatchling>=1.27.0",
    "ruff>=0.11.8",
    "morphological_torch ; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "pyrefly>=0.17.0",
]
